### ISSUE TITLE
Down mouse bug

### ISSUE THREAD

**Issue by MaximovInk** [DevChrome/Pixel-Engine#1]
1.Write this code
`
        private Point lastPos;

        public override void OnUpdate(float elapsed)
        {
            if (GetMouse(Mouse.Left).Down)
            {
                Point vector = new Point(MouseX, MouseY);
                DrawLine(lastPos, vector, Pixel.Random());
            }
            lastPos = new Point(MouseX, MouseY);
        }
`

2. Run and press left mouse button
3.Move your mouse away from the window
4. Release the mouse and move it to the window.
The button will be clamped, is this a bug?

P.S. Engine very awesome!! :3

**Comment by RMZeroFour** [comment]
Thanks for telling me about this! I found and fixed a couple more bugs related to this.
P.S. Thanks! I hope to improve it further.
